"""empty message

Revision ID: 56932d4d8488
Revises: 65c6322d9d9a
Create Date: 2023-01-04 16:18:41.772021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56932d4d8488'
down_revision = '65c6322d9d9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('author')
    # ### end Alembic commands ###
